#pragma once
#include <string_view>

enum class TokenType {
    END_OF_FILE, ERROR,
    L_PAREN, R_PAREN, L_BRACE, R_BRACE, L_BRACKET, R_BRACKET,
    SEMI, COMMA, DOT, ELLIPSIS,
    PLUS, SUB, STAR, SLASH, EQ, GT, LT, NOT, QUES, COLON,
    EQ_EQ, LT_EQ, GT_EQ, NOT_EQ, ARROW, AND, OR,
    BIT_AND, BIT_OR, PLUS_PLUS, SUB_SUB, CARET, PERCENT,
    LT_LT, GT_GT, GT_GT_GT,
    PLUS_EQ, SUB_EQ, STAR_EQ, SLASH_EQ,
    BIT_AND_EQ, BIT_OR_EQ, CARET_EQ, PERCENT_EQ,
    LT_LT_EQ, GT_GT_EQ, GT_GT_GT_EQ,
    BOOL, BYTE, SHORT, USHORT, INT, UINT, LONG, ULONG,
    FLOAT, DOUBLE, DECIMAL, CHAR, STRING,
    CHAR_LITERAL, INT_LITERAL, LONG_LITERAL, FLOAT_LITERAL, DOUBLE_LITERAL, STRING_LITERAL,
    IDENTIFIER,
    ASSERT, BREAK, CASE, CATCH, CLASS, COMPUTED, CONST, CONTINUE, DEFAULT,
    DO, ELSE, ENUM, EXTENDS, FALSE_KW, FINAL, FINALLY, FOR, GOTO, IF, IMPORT,
    LET, NEW, NULL_KW, PACKAGE, PRIVATE, PROTECTED, PUBLIC, RETURN, STATIC, STRUCT,
    SUPER, SWITCH, THIS, THROW, THROWS, TRUE_KW, TRY, VOID, WHILE
};

std::u16string_view getTokenName(TokenType type);
TokenType lookupToken(std::u16string_view name);
