rule("gen-macos-sdk-stubs")
    before_build(function (target)
        local gen = path.join(os.projectdir(), "compiler/codegen/SdkStubs.gen.cpp")

        function gen_macos_sdk_stubs(out_path, sdk_path)
            local function emit_empty()
                io.writefile(out_path, table.concat({
                    "// Auto-generated by xmake_tools.lua - no SDK available.",
                    "#include \"SdkStubs.h\"",
                    "namespace ens {",
                    "const SdkStub kSdkStubs[] = {};",
                    "const std::size_t kSdkStubsCount = 0;",
                    "}  // namespace ens",
                    "",
                }, "\n"))
            end

            if not sdk_path or sdk_path == "" then
                local out, err = try { function () return os.iorun("xcrun --sdk macosx --show-sdk-path") end }
                if out then sdk_path = out:trim() end
            end
            if not sdk_path or not os.isdir(sdk_path) then
                print("warning: macOS SDK not found; emitting empty SDK stubs")
                emit_empty()
                return
            end

            local libsystem = path.join(sdk_path, "usr/lib/libSystem.B.tbd")
            if not os.isfile(libsystem) then
                print(string.format("warning: libSystem.B.tbd not found in '%s'; emitting empty SDK stubs", sdk_path))
                emit_empty()
                return
            end

            local pairs_list = {{"usr/lib/libSystem.B.tbd", libsystem}}
            local sys_tbds = os.files(path.join(sdk_path, "usr/lib/system", "*.tbd"))
            table.sort(sys_tbds)
            for _, tbd in ipairs(sys_tbds) do
                table.insert(pairs_list, {"usr/lib/system/" .. path.filename(tbd), tbd})
            end

            -- Skip regeneration if the source set hasn't changed. Cache a fingerprint
            -- of (sdk_path, file sizes) in a comment at the top of the generated file.
            local fingerprint_parts = {sdk_path}
            for _, pair in ipairs(pairs_list) do
                local info = os.filesize(pair[2])
                table.insert(fingerprint_parts, string.format("%s:%d", pair[1], info))
            end
            local fingerprint = table.concat(fingerprint_parts, "|")
            if os.isfile(out_path) then
                local existing = io.readfile(out_path, { continuation = "" }) or ""
                if existing:find("// fingerprint: " .. fingerprint, 1, true) then
                    return
                end
            end

            local lines = {
                "// Auto-generated by xmake_tools.lua - do not edit.",
                "// fingerprint: " .. fingerprint,
                "#include \"SdkStubs.h\"",
                "",
                "namespace ens {",
                "",
            }
            for idx, pair in ipairs(pairs_list) do
                local data = io.readfile(pair[2], { encoding = "binary" })
                table.insert(lines, string.format("static const unsigned char kStub%d[] = {", idx - 1))
                local n = #data
                local row = {}
                for i = 1, n do
                    row[#row + 1] = string.format("0x%02x", data:byte(i))
                    if i % 16 == 0 or i == n then
                        table.insert(lines, "    " .. table.concat(row, ", ") .. ",")
                        row = {}
                    end
                end
                table.insert(lines, "};")
                table.insert(lines, "")
            end
            table.insert(lines, "const SdkStub kSdkStubs[] = {")
            for idx, pair in ipairs(pairs_list) do
                table.insert(lines, string.format(
                    "    {\"%s\", kStub%d, sizeof(kStub%d)},",
                    pair[1], idx - 1, idx - 1))
            end
            table.insert(lines, "};")
            table.insert(lines, string.format("const std::size_t kSdkStubsCount = %d;", #pairs_list))
            table.insert(lines, "")
            table.insert(lines, "}  // namespace ens")
            table.insert(lines, "")

            io.writefile(out_path, table.concat(lines, "\n"))
            print(string.format("generated %s (%d files)", out_path, #pairs_list))
        end

        gen_macos_sdk_stubs(gen)
        target:add("files", gen, { always_added = true })
    end)
